# Generated by Django 6.0.2 on 2026-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("completed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("checklist", "Checklist"),
                            ("onboarding", "Onboarding"),
                            ("offboarding", "Offboarding"),
                            ("handover", "Device Handover"),
                        ],
                        default="checklist",
                        max_length=50,
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=list, help_text="List of field definitions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
